general:
    Default: DARK_AQUA
    Nickname: AQUA
    Message: WHITE
    PermissionDeny: DARK_RED
nicknames:
MOTD:
    ingame: "Welcome to the server!"
    system: "&4<&5QuantumSurvival&4>"
PlayerData:
Bad-Words:
- fuck
- fuc
- fuk
- bitch
- terrible
- terible
- sex
- noob
- dic
- dik
- dick
- shit
- fucing
- fuking
- fuker
- fucer
- fucking
- fucker
