settings:
    enable:
        factions: true
        survival: true
        kitpvp: true
        skyfight: true
        creative: true
        welcomeMessage: true
        authme:
            dailyAuth: true
            autoLoginCmd: true
    ranking:
        enable: true
        prefix: true
    customJoinMessage: true
    customQuitMessage: true
config: