main: me.skorrloregaming.Server
name: SkorrloreGaming
version: 1
author: "Speentie8081"
depend: [Factions, WorldEdit, WorldGuard]
softdepend: [AuthMe, ProtocolSupport, ProtocolLib, mcMMO, Votifier]
commands:
    staffchat:
        description: Enter or leave the private staff chat
        aliases: sc
    vote:
        description: View a list of available vote portals
    effect:
        description: Enable or disable effects for your account
        aliases: [effects, particle, particles]
    debug:
        description: Enable or disable debugging of this plugin
    website:
        description: Link to our minecraft server website
        aliases: [store, forums, forum, apply]
    trails:
        description: Select or purchase a trail to use
        aliases: trail
    clear:
        description: On execution your inventory will be cleared
        aliases: [clearinventory, clearinv, ci]
    upgrade-kit:
        description: Upgrade the Starter kit to something even better
        aliases: [kit-upgrade, kit-upgrades, upgrades, upgrade]
    spawn-npc:
        description: Spawn a custom npc at your location
        aliases: [spawnnpc, snpc, npc]
    remove-npc:
        description: Unregister a custom npc from the server
        aliases: [removenpc, rm-npc, rmnpc]
    autologin:
        description: Toggle the autologin feature for your account
        aliases: autolog
    reset:
        description: Unregister a defined player from the server
    skull:
        description: Give yourself a skull based on player name
    getenchant:
        description: Returns the enchantment name of a given ID
    playtime:
        description: Retrieves the play time for a given player
        aliases: pt
    who:
        description: Retrieves information about a given player
    list:
        description: Lists the currently connected players
    build-time:
        description: Get compilation time of this plugin
    moderate:
        description: Toggle the administrative moderation mode
        aliases: mod
    rules:
        description: View the servers' defined rules
    motd:
        description: Temporarily change the MOTD for the server
    wild:
        description: Teleport yourself randomly in the wild
        aliases: rtp
    give:
        description: A special version of the vanilla command
        aliases: giveme
    rename:
        description: Rename the held item to specified
        aliases: rn
    opme:
        description: Op yourself for around one minute
    vanish:
        description: Hide yourself from other players
        aliases: v
    workbench:
        description: Your virtual crafting table
        aliases: [wb, craft]
    dispose:
        description: Trash your most useless items
        aliases: trash
    sign-edit:
        description: Edit specific lines on a sign
    chest:
        description: View someone's personal inventory
        aliases: [pv, echest, enderchest]
    inventorysee:
        description: View someone's legacy inventory
        aliases: invsee
    ping:
        description: Find your connection latency
        aliases: latency
    mute:
        description: Mute the specified player
    warning:
        description: Warn a specific player (max of 3)
        aliases: warn
    kick:
        description: Kicks the specified player
    ban:
        description: Bans the specified player
        aliases: ban-ip
    pardon:
        description: Unbans the specified player
    clearchat:
        description: Clear the server chat
        aliases: cc
    reboot:
        description: Server restart command
    say:
        description: Customized broadcast system
    activate-shop:
        description: Gives staff the activation wand
    reload-cfg:
        description: Reloads the configuration file
    kitpvp:
        description: Teleport to the kitpvp server
    skyfight:
        description: Teleport to the skyfight server
    creative:
        description: Teleport to the creative server
    factions:
        description: Teleport to the factions server
    hub:
        description: Teleport to the hub server
        aliases: lobby
    home:
        description: Teleport to your defined home
    sethome:
        description: Locally set your home location
    delhome:
        description: Remove your home from the server
    tpa:
        description: Teleport to anyone you want
    tpaccept:
        description: Accept a pending teleportation request
        aliases: tpyes
    shop:
        description: Teleport to the factions-shop server
    setzone:
        description: Declare a zone in memory
    warp:
        description: Teleport to a declared zone
    setrank:
        description: Change someones rank
    disable-plugin:
        description: Disable a plugin on the server
    enable-plugin:
        description: Enable a plugin on the server
    servers:
        description: Retrieves a list of the valid servers
    server:
        description: Teleport to the specified server
    reply:
        description: Message the person you last messaged
        aliases: r
    tell:
        description: Message a player on the server
        aliases: [msg, message, w, pm]
    stats:
        description: View the stats for the current minigame
    spawn:
        description: Teleport to the spawn for the current minigame
    kit:
        description: Pull the kit you want down from memory
    kits:
        description: View the kits for the current minigame
    balancetop:
        description: View the ranking of currency on given server
        aliases: baltop
    balance:
        description: View the balance you have in your account
        aliases: bal
    pay:
        description: Pay someone the specified amount of cash
    suicide:
        description: Pretty much /kill but integrated with the server
        aliases: kill