main: com.skorrloregaming.main.SkorrloreGaming
name: SkorrloreGaming
version: 1.0
commands:
    tokens:
        description: SkorrloreGaming
    skyfight:
        description: SkorrloreGaming
    unlock-gamemode:
        description: SkorrloreGaming
    report:
        description: SkorrloreGaming
    weaken:
        description: SkorrloreGaming
    unweaken:
        description: SkorrloreGaming
    survival:
        description: SkorrloreGaming
    teampvp:
        description: SkorrloreGaming
    creative:
        description: SkorrloreGaming
    mute:
        description: SkorrloreGaming
    unmute:
        description: SkorrloreGaming
    ping:
        description: SkorrloreGaming
    reboot:
        description: Restart your Minecraft Server
    sgreload:
        description: SkorrloreGaming
    rename:
        description: SkorrloreGaming
    stats:
        description: SkorrloreGaming
    msg:
        description: SkorrloreGaming
    cc:
        description: SkorrloreGaming
    clearchat:
        description: SkorrloreGaming
    nick:
        description: SkorrloreGaming
    nickname:
        description: SkorrloreGaming
    tpa:
        description: SkorrloreGaming
    enable-plugin:
        description: SkorrloreGaming
    disable-plugin:
        description: SkorrloreGaming
    ci:
        description: SkorrloreGaming
    tpaccept:
        description: SkorrloreGaming
    setzone:
        description: SkorrloreGaming
    tpyes:
        description: SkorrloreGaming
    store:
        description: SkorrloreGaming
    sfeed:
        description: SkorrloreGaming
    sfly:
        description: SkorrloreGaming
    sfixall:
        description: SkorrloreGaming
    heal:
        description: SkorrloreGaming
    tpahere:
        description: SkorrloreGaming
    spawn:
        description: SkorrloreGaming
    balance:
        description: SkorrloreGaming
    bal:
        description: SkorrloreGaming
    money:
        description: SkorrloreGaming
    vote:
        description: SkorrloreGaming
    rules:
        description: SkorrloreGaming
    afk:
        description: SkorrloreGaming
    kit:
        description: SkorrloreGaming
    kits:
        description: SkorrloreGaming
    hub:
        description: SkorrloreGaming
    sethub:
        description: SkorrloreGaming
    getplayerip:
        description: SkorrloreGaming
    setrank:
        description: SkorrloreGaming
    server:
        description: SkorrloreGaming
    pay:
        description: SkorrloreGaming
    sethome:
        description: SkorrloreGaming
    home:
        description: SkorrloreGaming
    delhome:
        description: SkorrloreGaming