name: Q-S
main: com.sg.qs.QuantumSurvival.QuantumSurvival
version: 10.16.14
description: Another Bukkit Plugin
commands:
  qgive:
     description: Base plugin command.
  qenchant:
     description: Base plugin command.
  qhat:
     description: Base plugin command.
  qgod:
     description: Base plugin command.
  qmute:
     description: Base plugin command.
  qvanish:
     description: Base plugin command.
  qnick:
     description: Base plugin command.
  qsetmotd:
     description: Base plugin command.
  qban:
     description: Base plugin command.
  qkick:
     description: Base plugin command.
  qdeop:
     description: Base plugin command.
  qop:
     description: Base plugin command.
  qheal:
     description: Base plugin command.
  qgm:
     description: Base plugin command.
  qfeed:
     description: Base plugin command.
  qxp:
     description: Base plugin command.
  qclear:
     description: Base plugin command.
  qkill:
     description: Base plugin command.
  qrepair:
     description: Base plugin command.
  qpinfo:
     description: Base plugin command.
  qsmite:
     description: Base plugin command.
  qbroadcast:
     description: Base plugin command.
  qsuicide:
     description: Base plugin command.
  qhelp:
     description: Base plugin command.
  qclearchat:
     description: Base plugin command.
  qfakejoin:
     description: Base plugin command.
  qfakeleave:
     description: Base plugin command.
  qfly:
     description: Base plugin command.
  qsetspawn:
     description: Base plugin command.
  qspawn:
     description: Base plugin command.
  qreload:
     description: Base plugin command.