main: com.skorrloregaming.main.SkorrloreGaming
name: SkorrloreGaming
version: 1.0
commands:
    disable-plugin:
        description: SkorrloreGaming
    enable-plugin:
        description: SkorrloreGaming
    tpa:
        description: SkorrloreGaming
    toggle-saved-items:
        description: SkorrloreGaming
    auc-end:
        description: SkorrloreGaming
    tpaccept:
        description: SkorrloreGaming
    setzone:
        description: SkorrloreGaming
    tpyes:
        description: SkorrloreGaming
    bid:
        description: SkorrloreGaming
    auc-start:
        description: SkorrloreGaming
    gm:
        description: SkorrloreGaming
    code-gen:
        description: SkorrloreGaming
    donate:
        description: SkorrloreGaming
    god:
        description: SkorrloreGaming
    ungod:
        description: SkorrloreGaming
    heal:
        description: SkorrloreGaming
    tpahere:
        description: SkorrloreGaming
    spawn:
        description: SkorrloreGaming
    balance:
        description: SkorrloreGaming
    bal:
        description: SkorrloreGaming
    ban:
        description: SkorrloreGaming
    def-kit:
        description: SkorrloreGaming
    money:
        description: SkorrloreGaming
    vote:
        description: SkorrloreGaming
    rules:
        description: SkorrloreGaming
    afk:
        description: SkorrloreGaming
    kit:
        description: SkorrloreGaming
    kits:
        description: SkorrloreGaming
    hub:
        description: SkorrloreGaming
    sethub:
        description: SkorrloreGaming
    getPlayerIp:
        description: SkorrloreGaming
    setrank:
        description: SkorrloreGaming
    server:
        description: SkorrloreGaming
    pay:
        description: SkorrloreGaming
    respawn:
        description: SkorrloreGaming
    addperm:
        description: SkorrloreGaming
    sethome:
        description: SkorrloreGaming
    home:
        description: SkorrloreGaming
    delhome:
        description: SkorrloreGaming